import type {
  Lead,
  CaseStudy,
  KpiData,
  ZoneData,
  MonthlyData,
  HabitScenario,
} from "@/types";

export const mockLeads: Lead[] = [
  {
    id: "1",
    name: "Familia Rodríguez",
    commune: "Limache",
    region: "V",
    propertyType: "parcela",
    monthlyBill: 180000,
    priority: "independencia",
    potentialSaving: 126000,
    status: "evaluacion",
    projectValue: 6800000,
    phone: "+56912345678",
    createdAt: "2026-05-01",
    notes: "Parcela 5000m², bomba de agua, interesados en respaldo total",
  },
  {
    id: "2",
    name: "Cabañas El Sol",
    commune: "Algarrobo",
    region: "V",
    propertyType: "turismo",
    monthlyBill: 320000,
    priority: "ahorro",
    potentialSaving: 224000,
    status: "propuesta",
    projectValue: 12500000,
    email: "contacto@cabanassol.cl",
    createdAt: "2026-05-03",
    notes: "8 cabañas, piscina, requieren autonomía en temporada alta",
  },
  {
    id: "3",
    name: "Camila Morales",
    commune: "Maipú",
    region: "RM",
    propertyType: "hogar",
    monthlyBill: 95000,
    priority: "ahorro",
    potentialSaving: 62000,
    status: "contactado",
    projectValue: 3900000,
    phone: "+56987654321",
    createdAt: "2026-05-05",
  },
  {
    id: "4",
    name: "Supermercado Pérez",
    commune: "Rancagua",
    region: "VI",
    propertyType: "negocio",
    monthlyBill: 580000,
    priority: "respaldo",
    potentialSaving: 406000,
    status: "nuevo",
    projectValue: 22000000,
    email: "gerencia@smpérez.cl",
    createdAt: "2026-05-08",
  },
  {
    id: "5",
    name: "Agrícola Los Andes",
    commune: "Machalí",
    region: "VI",
    propertyType: "agricola",
    monthlyBill: 450000,
    priority: "independencia",
    potentialSaving: 315000,
    status: "evaluacion",
    projectValue: 18500000,
    createdAt: "2026-05-10",
    notes: "Riego automatizado, 3 bombas, requieren respaldo 24h",
  },
  {
    id: "6",
    name: "Jorge Núñez",
    commune: "Colina",
    region: "RM",
    propertyType: "parcela",
    monthlyBill: 220000,
    priority: "plusvalia",
    potentialSaving: 154000,
    status: "cerrado",
    projectValue: 8200000,
    createdAt: "2026-04-20",
  },
  {
    id: "7",
    name: "Hotel Casablanca",
    commune: "Casablanca",
    region: "V",
    propertyType: "turismo",
    monthlyBill: 680000,
    priority: "ahorro",
    potentialSaving: 476000,
    status: "nuevo",
    projectValue: 28000000,
    createdAt: "2026-05-12",
  },
  {
    id: "8",
    name: "María González",
    commune: "Olmué",
    region: "V",
    propertyType: "hogar",
    monthlyBill: 130000,
    priority: "respaldo",
    potentialSaving: 91000,
    status: "contactado",
    projectValue: 5100000,
    createdAt: "2026-05-11",
  },
];

export const mockCases: CaseStudy[] = [
  {
    id: "1",
    title: "Parcela Familiar en Limache",
    type: "parcela",
    location: "Limache",
    region: "V",
    monthlyBillBefore: 180000,
    monthlyBillAfter: 32000,
    saving: 148000,
    roiYears: 4.1,
    mainBenefit: "Independencia total + respaldo ante cortes",
    description:
      "Familia con parcela de 4.000m², bomba de agua, gallinero y taller. Antes dependían 100% de la red. Hoy generan el 82% de su consumo y el excedente vuelve al sistema.",
    system: "10 paneles + 2 baterías + inversor híbrido",
    image: "/cases/limache.jpg",
  },
  {
    id: "2",
    title: "Cabañas Turísticas Algarrobo",
    type: "turismo",
    location: "Algarrobo",
    region: "V",
    monthlyBillBefore: 320000,
    monthlyBillAfter: 58000,
    saving: 262000,
    roiYears: 3.8,
    mainBenefit: "Ahorro en temporada alta + diferencial competitivo",
    description:
      "Complejo de 6 cabañas con piscina. La inversión en solar se convirtió en argumento de venta: 'cabañas con energía limpia'. Temporada alta cubierta al 90%.",
    system: "18 paneles + 3 baterías + inversor trifásico",
    image: "/cases/algarrobo.jpg",
  },
  {
    id: "3",
    title: "Casa Familiar Maipú",
    type: "hogar",
    location: "Maipú",
    region: "RM",
    monthlyBillBefore: 95000,
    monthlyBillAfter: 28000,
    saving: 67000,
    roiYears: 4.8,
    mainBenefit: "Ahorro mensual garantizado desde mes 1",
    description:
      "Hogar de 4 personas con teletrabajo. El cambio de hábitos (electrodomésticos en horario solar) aumentó el retorno en un 30% adicional.",
    system: "6 paneles + 1 batería + inversor monofásico",
    image: "/cases/maipu.jpg",
  },
  {
    id: "4",
    title: "Negocio Retail Rancagua",
    type: "negocio",
    location: "Rancagua",
    region: "VI",
    monthlyBillBefore: 580000,
    monthlyBillAfter: 95000,
    saving: 485000,
    roiYears: 3.2,
    mainBenefit: "Continuidad operacional + ahorro masivo",
    description:
      "Supermercado con cámaras de frío y alta carga eléctrica. Los cortes eléctricos costaban ventas. Hoy tienen respaldo completo y el ROI más rápido de su cartera.",
    system: "24 paneles + 4 baterías + inversor industrial",
    image: "/cases/rancagua.jpg",
  },
];

export const mockKPIs: KpiData[] = [
  {
    label: "Leads Activos",
    value: 7,
    unit: "clientes",
    trend: 12,
    icon: "Users",
    color: "text-blue-400",
  },
  {
    label: "Instalaciones Este Mes",
    value: 3,
    unit: "proyectos",
    trend: 50,
    icon: "Zap",
    color: "text-amber-400",
  },
  {
    label: "kWh Proyectados/Mes",
    value: "48.200",
    unit: "kWh",
    trend: 8,
    icon: "Sun",
    color: "text-yellow-400",
  },
  {
    label: "Ahorro Total Proyectado",
    value: "$1.653.000",
    unit: "CLP/mes",
    trend: 23,
    icon: "TrendingUp",
    color: "text-green-400",
  },
  {
    label: "Pipeline Comercial",
    value: "$97.000.000",
    unit: "CLP",
    trend: 15,
    icon: "DollarSign",
    color: "text-purple-400",
  },
  {
    label: "Tasa de Cierre",
    value: "68%",
    trend: 5,
    icon: "Target",
    color: "text-orange-400",
  },
];

export const mockZones: ZoneData[] = [
  { name: "Limache", region: "V", lat: -33.0, lng: -71.1, clientType: ["parcela", "hogar"], opportunity: "alta", potentialLeads: 45, avgBill: 160000, mainNeed: "Independencia + respaldo" },
  { name: "Olmué", region: "V", lat: -33.0, lng: -71.0, clientType: ["parcela", "turismo"], opportunity: "alta", potentialLeads: 30, avgBill: 140000, mainNeed: "Cortes frecuentes" },
  { name: "Casablanca", region: "V", lat: -33.3, lng: -71.4, clientType: ["agricola", "turismo"], opportunity: "alta", potentialLeads: 38, avgBill: 280000, mainNeed: "Riego + cabañas" },
  { name: "Algarrobo", region: "V", lat: -33.4, lng: -71.7, clientType: ["turismo", "hogar"], opportunity: "alta", potentialLeads: 52, avgBill: 220000, mainNeed: "Turismo + segunda vivienda" },
  { name: "Santo Domingo", region: "V", lat: -33.6, lng: -71.6, clientType: ["turismo", "parcela"], opportunity: "media", potentialLeads: 28, avgBill: 190000, mainNeed: "Veraneo + respaldo" },
  { name: "Rancagua", region: "VI", lat: -34.2, lng: -70.7, clientType: ["negocio", "pyme"], opportunity: "alta", potentialLeads: 65, avgBill: 450000, mainNeed: "Continuidad operacional" },
  { name: "Machalí", region: "VI", lat: -34.2, lng: -70.6, clientType: ["agricola", "parcela"], opportunity: "alta", potentialLeads: 40, avgBill: 320000, mainNeed: "Riego y bombas" },
  { name: "Chicureo", region: "RM", lat: -33.2, lng: -70.7, clientType: ["hogar", "parcela"], opportunity: "alta", potentialLeads: 70, avgBill: 210000, mainNeed: "Plusvalía + ahorro" },
  { name: "Colina", region: "RM", lat: -33.2, lng: -70.7, clientType: ["parcela", "hogar"], opportunity: "media", potentialLeads: 55, avgBill: 180000, mainNeed: "Independencia energética" },
  { name: "Lampa", region: "RM", lat: -33.3, lng: -70.9, clientType: ["agricola", "pyme"], opportunity: "media", potentialLeads: 35, avgBill: 250000, mainNeed: "Costos operativos" },
  { name: "Buin", region: "RM", lat: -33.7, lng: -70.7, clientType: ["agricola", "parcela"], opportunity: "media", potentialLeads: 42, avgBill: 200000, mainNeed: "Bombas + riego" },
  { name: "Maipú", region: "RM", lat: -33.5, lng: -70.8, clientType: ["hogar", "pyme"], opportunity: "media", potentialLeads: 90, avgBill: 95000, mainNeed: "Ahorro mensual" },
];

export const mockMonthlyData: MonthlyData[] = [
  { month: "Ene", kwhGenerated: 6200, savings: 186000, leads: 8 },
  { month: "Feb", kwhGenerated: 5900, savings: 177000, leads: 6 },
  { month: "Mar", kwhGenerated: 5100, savings: 153000, leads: 9 },
  { month: "Abr", kwhGenerated: 4300, savings: 129000, leads: 7 },
  { month: "May", kwhGenerated: 3800, savings: 114000, leads: 11 },
  { month: "Jun", kwhGenerated: 3200, savings: 96000, leads: 5 },
  { month: "Jul", kwhGenerated: 3400, savings: 102000, leads: 8 },
  { month: "Ago", kwhGenerated: 4100, savings: 123000, leads: 10 },
  { month: "Sep", kwhGenerated: 4800, savings: 144000, leads: 12 },
  { month: "Oct", kwhGenerated: 5500, savings: 165000, leads: 14 },
  { month: "Nov", kwhGenerated: 6100, savings: 183000, leads: 13 },
  { month: "Dic", kwhGenerated: 6400, savings: 192000, leads: 9 },
];

export const mockHabits: HabitScenario[] = [
  {
    id: "lavadora",
    appliance: "Lavadora",
    icon: "🫧",
    timeDay: "12:00 – 15:00",
    timeNight: "22:00 – 24:00",
    impactLabel: "Hasta +18% retorno",
    impactPercent: 18,
  },
  {
    id: "lavavajillas",
    appliance: "Lavavajillas",
    icon: "🍽️",
    timeDay: "13:00 – 14:00",
    timeNight: "21:00 – 22:00",
    impactLabel: "Hasta +12% retorno",
    impactPercent: 12,
  },
  {
    id: "piscina",
    appliance: "Bomba Piscina",
    icon: "🏊",
    timeDay: "10:00 – 14:00",
    timeNight: "20:00 – 22:00",
    impactLabel: "Hasta +25% retorno",
    impactPercent: 25,
  },
  {
    id: "carga",
    appliance: "Carga Dispositivos",
    icon: "🔌",
    timeDay: "11:00 – 14:00",
    timeNight: "23:00 – 01:00",
    impactLabel: "Hasta +8% retorno",
    impactPercent: 8,
  },
  {
    id: "calefon",
    appliance: "Calefón Eléctrico",
    icon: "🚿",
    timeDay: "11:00 – 13:00",
    timeNight: "19:00 – 20:00",
    impactLabel: "Hasta +22% retorno",
    impactPercent: 22,
  },
];

export const WHATSAPP_NUMBER = "+56995019476";
export const CONTACT_EMAIL = "Solergy.soluciones@gmail.com";
export const WHATSAPP_URL = `https://wa.me/56995019476?text=Hola%20Solergy%2C%20me%20interesa%20evaluar%20energ%C3%ADa%20solar%20para%20mi%20propiedad.`;
